language: objective-c
osx_image: xcode9.4

script:
  - xcodebuild clean test -project cleanNews.xcodeproj -scheme cleanNewsTest -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet